---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Broulf's Dashboard"
subtitle: "Life is accepting what is and working from that -Gloria Naylor"
logo: "logo.png"

header: true
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
footer: false

# Optional theme customization
theme: dark
colors:
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Hello !"
#  icon: "fab fa-audible"
#  content: "This is Broulf's easy-manage server dashboard, to be used for accessing media, files, and other application based utilities at the ease and convenience of this dashboard."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Blog"
    icon: "fas fa-server"
    url: "/blog/index.html"
  - name: "Cox"
    icon: "fas fa-server"
    url: "https://wifi.cox.com"
  - name: "Local"
    icon: "fas fa-server"
    url: "http://192.168.0.1"
  - name: "Wikipedia"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Crunchyroll"
        logo: "assets/icons/crunchyroll.svg"
        subtitle: "Anime streaming site"
        tag: "media"
        url: "https://beta.crunchyroll.com"
      - name: "Disney+"
        logo: "assets/icons/disney.svg"
        subtitle: "Disney movie streaming site"
        tag: "media"
        url: "https://disneyplus.com/"
      - name: "Netflix"
        logo: "assets/icons/netflix.webp"
        subtitle: "That lame website for movie streaming"
        tag: "media"
        url: "https://netflix.com"
      - name: "Plex"
        logo: "assets/icons/plex.webp"
        subtitle: "Plex Media Server"
        tag: "media"
        url: "http://plex.broulf.org"
      - name: "Spotify"
        logo: "assets/icons/spotify.svg"
        subtitle: "Music streaming website place"
        tag: "media"
        url: "https://open.spotify.com/"
      - name: "Twitch"
        logo: "assets/icons/twitch.png"
        subtitle: "That Just Chatting website"
        tag: "media"
        url: "https://twitch.tv"
      - name: "Youtube"
        logo: "assets/icons/youtube.svg"
        subtitle: "Youtube, yeah, youtube"
        tag: "media"
        url: "https://youtube.com"
      - name: "YTS"
        logo: "assets/icons/movie.jpg"
        subtitle: "Totally legal movie website"
        tag: "media"
        url: "https://yts.mx"
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "2FA"
        logo: "assets/icons/bitwarden.png"
        subtitle: "Custom 2FA application"
        tag: "app"
        url: "https://factor.broulf.org"
      - name: "Bitwarden"
        logo: "assets/icons/bitwarden.png"
        subtitle: "Bitwarden Password Manager"
        tag: "app"
        url: "https://vault.bitwarden.com"
      - name: "Chase"
        logo: "assets/icons/chase.png"
        subtitle: "Chase Bank"
        tag: "app"
        url: "https://chase.com/"
      - name: "Cloudflare"
        logo: "assets/icons/cloudflare.svg"
        subtitle: "Cloudflare DNS Website"
        tag: "app"
        url: "https://www.cloudflare.com/login"
      - name: "Github"
        logo: "assets/icons/github.svg"
        subtitle: "My Github account"
        tag: "app"
        url: "https://github.com/Broulf"
      - name: "Oracle Cloud"
        logo: "assets/icons/oracle.svg"
        subtitle: "Oracle Cloud Hosting"
        tag: "app"
        url: "https://cloud.oracle.com/"
      - name: "Playit"
        logo: "assets/icons/playit.png"
        subtitle: "Basically, my router"
        tag: "app"
        url: "https://playit.gg/account"
      - name: "Proton VPN"
        logo: "assets/icons/proton.svg"
        subtitle: "Proton VPN, a pretty nice VPN"
        tag: "app"
        url: "https://account.protonvpn.com/login"
      - name: "Server Status"
        logo: "assets/tools/sample2.png"
        subtitle: "Quick and easy Server Status checker"
        tag: "app"
        url: "http://status.broulf.org"
      - name: "Speedtest"
        logo: "assets/icons/speedtest.svg"
        subtitle: "OOKLA Speedtest Website"
        tag: "app"
        url: "https://speedtest.net"
      - name: "Twitter"
        logo: "assets/icons/twitter.png"
        subtitle: "That website with INCREDIBLE takes"
        tag: "app"
        url: "https://twitter.com"
  - name: "Files"
    icon: "fas fa-file-alt"
    items:
      - name: "0bin"
        logo: "assets/icons/pastebin.png"
        subtitle: "PasteBin Altternative"
        tag: "file"
        url: "https://paste.broulf.org"
      - name: "CSGO Config"
        logo: "assets/icons/pastebin.png"
        subtitle: "My CSGO Config"
        tag: "file"
        url: "https://paste.broulf.org/paste/rpTCMk2W#hNwIRMr1O3sH4YimrXE0bDh-dW5HAJDlutl6XZ6z9X4"
      - name: "CyberChef"
        logo: "assets/icons/pastebin.png"
        subtitle: "Use recipes to quickly encrypt files"
        tag: "file"
        url: "https://encrypt.broulf.org"
      - name: "Google Drive"
        logo: "assets/icons/googledrive.svg"
        subtitle: "Google Drive Storage"
        tag: "file"
        url: "https://drive.google.com"
      - name: "Ninite"
        logo: "assets/tools/sample.png"
        subtitle: "Ninite Installer"
        tag: "file"
        url: "https://ninite.com"
  - name: "Gaming"
    icon: "fas fa-headset"
    items:
      - name: "Curseforge"
        logo: "assets/icons/curse.svg"
        subtitle: "Minecraft Curseforge"
        tag: "gaming"
        url: "https://www.curseforge.com/minecraft/mc-mods"
      - name: "ESEA"
        logo: "assets/icons/esea.png"
        subtitle: "ESEA CSGO"
        tag: "gaming"
        url: "https://play.esea.net/users/2307500"
      - name: "Faceit"
        logo: "assets/icons/faceit.webp"
        subtitle: "Faceit CSGO"
        tag: "gaming"
        url: "https://www.faceit.com/en/players/Broulf"
      - name: "Steam"
        logo: "assets/icons/steam.svg"
        subtitle: "Steam Website"
        tag: "gaming"
        url: "https://steamcommunity.com/id/broulf/"
  - name: "Other"
    icon: "fas fa-book"
    items:
      - name: "Gmail"
        logo: "assets/icons/gmail.svg"
        subtitle: "Google Mail"
        tag: "school"
        url: "https://mail.google.com"
      - name: "Moodle"
        logo: "assets/icons/ul.webp"
        subtitle: "UL Moodle"
        tag: "school"
        url: "https://moodle.louisiana.edu"
      - name: "Outlook"
        logo: "assets/icons/outlook.svg"
        subtitle: "Outlook Mail"
        tag: "email"
        url: "https://outlook.office.com/mail/"
      - name: "ULink"
        logo: "assets/icons/ul.webp"
        subtitle: "UL ULink"
        tag: "school"
        url: "https://ulink.louisiana.edu/"
