---
title: "Homer Theme"
subtitle: "Walkx"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

links:
  - name: ""
    icon: "fa fa-shield"
    url: "https://2fa.broulf.org"
  - name: ""
    icon: "fas fa-book"
    url: "https://broulf.org/blog"
  - name: ""
    icon: "fab fa-docker"
    url: "https://docker.broulf.org"
  - name: ""
    icon: "fas fa-list-ol"
    url: "https://inv.broulf.org"
  - name: ""
    icon: "fas fa-paste"
    url: "https://paste.broulf.org"
  - name: ""
    icon: "fa fa-rss"
    url: "https://broulf.org/feed"
  - name: ""
    icon: "fab fa-wikipedia-w"
    url: "https://www.wikipedia.org/"
  - name: ""
    icon: "fas fa-download"
    url: "https://ytdl.broulf.org"

services:
  - name: "//Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Chase"
        logo: "assets/icons/chase.png"
        subtitle: "Chase Bank"
        tag: "app"
        url: "https://chase.com/"
      - name: "Cloudflare"
        logo: "assets/icons/cloudflare.svg"
        subtitle: "Cloudflare DNS Website"
        tag: "app"
        url: "https://www.cloudflare.com/login"
      - name: "Github"
        logo: "assets/icons/github.svg"
        subtitle: "My Github account"
        tag: "app"
        url: "https://github.com/Broulf"
      - name: "Ninite"
        logo: "assets/tools/sample.png"
        subtitle: "Ninite Installer"
        tag: "file"
        url: "https://ninite.com"
      - name: "Oracle Cloud"
        logo: "assets/icons/oracle.svg"
        subtitle: "Oracle Cloud Hosting"
        tag: "app"
        url: "https://cloud.oracle.com/"
      - name: "Proton VPN"
        logo: "assets/icons/proton.svg"
        subtitle: "Proton VPN, a pretty nice VPN"
        tag: "app"
        url: "https://account.protonvpn.com/login"
      - name: "Server Status"
        logo: "assets/tools/sample2.png"
        subtitle: "Quick and easy Server Status checker"
        tag: "app"
        url: "http://status.broulf.org"
      - name: "Speedtest"
        logo: "assets/icons/speedtest.svg"
        subtitle: "OOKLA Speedtest Website"
        tag: "app"
        url: "https://speedtest.net"
      - name: "Twitter"
        logo: "assets/icons/twitter.png"
        subtitle: "That website with INCREDIBLE takes"
        tag: "app"
        url: "https://twitter.com"
  - name: "//Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Crunchyroll"
        logo: "assets/icons/crunchyroll.svg"
        subtitle: "Anime streaming site"
        tag: "media"
        url: "https://beta.crunchyroll.com"
      - name: "Disney+"
        logo: "assets/icons/disney.svg"
        subtitle: "Disney movie streaming site"
        tag: "media"
        url: "https://disneyplus.com/"
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.png"
        subtitle: "Plex Media Server"
        tag: "media"
        url: "http://broulf.us:8096"
      - name: "Netflix"
        logo: "assets/icons/netflix.webp"
        subtitle: "That lame website for movie streaming"
        tag: "media"
        url: "https://netflix.com"
      - name: "Plex"
        logo: "assets/icons/plex.webp"
        subtitle: "Plex Media Server"
        tag: "media"
        url: "http://plex.broulf.org"
      - name: "Spotify"
        logo: "assets/icons/spotify.svg"
        subtitle: "Music streaming website place"
        tag: "media"
        url: "https://open.spotify.com/"
      - name: "Twitch"
        logo: "assets/icons/twitch.png"
        subtitle: "That Just Chatting website"
        tag: "media"
        url: "https://twitch.tv"
      - name: "Youtube"
        logo: "assets/icons/youtube.svg"
        subtitle: "Youtube, yeah, youtube"
        tag: "media"
        url: "https://youtube.com"
      - name: "YTS"
        logo: "assets/icons/movie.jpg"
        subtitle: "Totally legal movie website"
        tag: "media"
        url: "https://yts.mx"